/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ThuXuatDAO;
import controller.VuKhiDAO;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modul.ThuXuat;

/**
 *
 * @author LeeĐăgg
 */
public class HomeFrm2 extends javax.swing.JFrame {

    /**
     * Creates new form Home2Frm
     */
    private ArrayList<ThuXuat> list;
    private List<ThuXuat> thuXuats;
    private DefaultTableModel tblModel2;
    private String selectedVuKhiName;
    private int selectedIndex;
    private ThuXuatDAO dao;
    public HomeFrm2(JFrame parent, boolean modal) {
       initComponents();
        this.setLocationRelativeTo(parent);
        initializeFields();
        loadThuXuats();
    }
     public HomeFrm2(String selectedVuKhiName) {
        initComponents();
        this.setLocationRelativeTo(null); // Nếu cần, có thể bỏ hoặc thay đổi
        this.selectedVuKhiName = selectedVuKhiName;
        lblTenVuKhi.setText(selectedVuKhiName); // Hiển thị tên vũ khí trên label
        initializeFields();
        loadThuXuats();
    }

    private HomeFrm2() {
     initComponents();
        this.setLocationRelativeTo(null);
        list = new ThuXuatDAO().getListThuXuat();
        initializeFields();
        this.setTitle("Bảng Thu ");
        loadThuXuats();
    }
    private void initializeFields() {
        thuXuats = new ArrayList<>();
        tblModel2 = (DefaultTableModel) tblThuXuat.getModel();
    }
    private void loadDataToTable(){
        thuXuats = dao.getListThuXuat();
        tblModel2.setRowCount(0);
        for (ThuXuat thuXuat : thuXuats) {tblModel2.addRow(new Object[]{thuXuat.getTenVuKhi(), thuXuat.getNgay(), thuXuat.getHanhDong(), thuXuat.getSoLuong(), thuXuat.getSoLuongDan()});
        }
    }
    public void showData(){
        tblModel2.setRowCount(0);
        for (ThuXuat thuXuat : thuXuats) {
            tblModel2.addRow(new Object[]{thuXuat.getTenVuKhi(), thuXuat.getNgay(), thuXuat.getHanhDong(), thuXuat.getSoLuong(), thuXuat.getSoLuongDan()});
        }
        
    }
    public void addThuXuat(ThuXuat t){
        thuXuats.add(t);
        showData();
    }
    private void saveThuXuats() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("thuXuats.dat"))) {
            oos.writeObject(thuXuats);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void loadThuXuats() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("thuXuats.dat"))) {
            thuXuats = (List<ThuXuat>) ois.readObject();
            for (ThuXuat thuXuat : thuXuats) {
                tblModel2.addRow(new Object[]{thuXuat.getTenVuKhi(), thuXuat.getNgay(), thuXuat.getHanhDong(), thuXuat.getSoLuong(), thuXuat.getSoLuongDan()});
            }
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cbxHanhDong = new javax.swing.JComboBox<>();
        txtSoLuong = new java.awt.TextField();
        txtSoLuongDan = new java.awt.TextField();
        btnAdd = new java.awt.Button();
        btnEdit = new java.awt.Button();
        btnDel = new java.awt.Button();
        btnExit = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuXuat = new javax.swing.JTable();
        lblTenVuKhi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(153, 255, 204));
        label1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        label1.setText("Bảng Thu Xuất Vũ Khí");

        label2.setText("Tên Vũ Khí");

        label3.setText("Ngày");

        label4.setText("Hành Động");

        label5.setText("Số Lượng");

        label6.setText("Số Lượng Đạn");

        cbxHanhDong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xuất", "Thu" }));

        btnAdd.setLabel("Thực Hiện");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setLabel("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDel.setLabel("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnExit.setLabel("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tblThuXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Vũ Khí", "Ngày", "Hành Động", "Số Lượng", "Số Lượng Đạn"
            }
        ));
        jScrollPane1.setViewportView(tblThuXuat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoLuongDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxHanhDong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(lblTenVuKhi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenVuKhi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxHanhDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label2.getAccessibleContext().setAccessibleName("");
        label3.getAccessibleContext().setAccessibleName("");
        label4.getAccessibleContext().setAccessibleName("");
        label5.getAccessibleContext().setAccessibleName("");
        label6.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    String tenVuKhi = lblTenVuKhi.getText();
    String hanhDong = cbxHanhDong.getSelectedItem().toString();
    int soLuong = 0, soLuongDan = 0;
    Date ngay = jDateChooser1.getDate();
    boolean isOK = true;

    if (tenVuKhi == null || tenVuKhi.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn Tên Vũ Khí!");
        isOK = false;
    }

    if (ngay == null) {
        JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn Ngày!");
        isOK = false;
    }

    try {
        soLuong = Integer.parseInt(txtSoLuong.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Số Lượng không hợp lệ!");
        isOK = false;
    }

    try {
        soLuongDan = Integer.parseInt(txtSoLuongDan.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Số Lượng Đạn không hợp lệ!");
        isOK = false;
    }

    if (isOK) {
        ThuXuat thuXuat = new ThuXuat(tenVuKhi, hanhDong, ngay, soLuong, soLuongDan);
        addThuXuat(thuXuat); // Thêm thuXuat vào danh sách thuXuats
        JOptionPane.showMessageDialog(rootPane, "Đã Thực Hiện!");
    }
        showData();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       
        this.dispose();
        saveThuXuats();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int removeIndex = tblThuXuat.getSelectedRow();
        if(removeIndex == -1){
            JOptionPane.showMessageDialog(rootPane, "Chọn vũ khí cần xóa!");
        }else if(thuXuats.size() == 0 ){
        JOptionPane.showMessageDialog(rootPane, "Không có vũ khí để xóa!");
}   else{
            thuXuats.remove(removeIndex);
            showData();
        }  
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        selectedIndex = tblThuXuat.getSelectedRow();
        if(thuXuats.size() == 0 ){
            JOptionPane.showMessageDialog(rootPane, "Hãy thêm hành động!");
            
        }else if(selectedIndex == -1  ){
             JOptionPane.showMessageDialog(rootPane, "Hãy chọn phần cần sửa!");
        }
        else{
            EditFrm2 edit = new EditFrm2(this, rootPaneCheckingEnabled);
            edit.setEditData(thuXuats.get(selectedIndex));
            edit.setVisible(true);
        }
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAdd;
    private java.awt.Button btnDel;
    private java.awt.Button btnEdit;
    private java.awt.Button btnExit;
    private javax.swing.JComboBox<String> cbxHanhDong;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JLabel lblTenVuKhi;
    private javax.swing.JTable tblThuXuat;
    private java.awt.TextField txtSoLuong;
    private java.awt.TextField txtSoLuongDan;
    // End of variables declaration//GEN-END:variables

    public void updateThuXuat(ThuXuat thuXuat) {
        thuXuats.remove(selectedIndex);
        this.addThuXuat(thuXuat);
    }
}
